import Head from 'next/head'
import {Inter} from 'next/font/google'
import Header from '@/modules/header/Header'
import HomePage from '@/modules/homePage/HomePage'
import About from '@/modules/about/About'
import LatestProjects from '@/modules/latestProjects/LatestProjects'
import Skills from '@/modules/skills/Skills'
import Footer from '@/modules/footer/Footer'
import ContactInfo from '@/modules/contactInfo/ContactInfo'
import SubmitModel from '@/modules/submitModel/SubmitModel'

const inter = Inter({subsets: ['latin']})

interface MyIdInterface {
  id: string
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <HomePage id='home' />
      <About id='about' />
      <LatestProjects id='projects' />
      <Skills id='skills' />
      <ContactInfo id='contact' />
      <Footer />
    </>
  )
}
